name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (requirements + pytest)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
          python -m pip install --upgrade pytest

      - name: Show env
        run: |
          python -V
          python -c "import sys; print('exe:', sys.executable)"
          python -c "import pkgutil; print('has pytest:', bool(pkgutil.find_loader('pytest')))"
          python -c "import fastapi, pydantic; print('fastapi', fastapi.__version__, 'pydantic', pydantic.__version__)"

      - name: Run pytest
        env:
          UNIT_TEST: "1"
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q
